---

- name: "Bind ServiceAccount {{ service_account }} to ClusterRole {{ role_to_bind }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ service_account }}-{{ role_to_bind }}-binding"
      subjects:
        - kind: ServiceAccount
          name: "{{ service_account }}"
          namespace: "{{ namespace }}"
      roleRef:
        kind: ClusterRole
        name: "{{ role_to_bind }}"
        apiGroup: rbac.authorization.k8s.io
  when: binding_type in ["clusterrole_existing", "clusterrole_new"]


- name: "Bind ServiceAccount {{ service_account }} to Role {{ role_to_bind }} in namespace {{ namespace }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: "{{ service_account }}-{{ role_to_bind }}-binding"
        namespace: "{{ namespace }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ service_account }}"
          namespace: "{{ namespace }}"
      roleRef:
        kind: Role
        name: "{{ role_to_bind }}"
        apiGroup: rbac.authorization.k8s.io
  when: binding_type in ["role_existing", "role_new"]

