---
- name: "Create ServiceAccount for {{ username }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ service_account }}"
        namespace: "{{ namespace }}"

