---

- name: "Upload kubeconfig for {{ username }} to S3"
  amazon.aws.s3_object:
    bucket: "{{ s3_bucket }}"
    object: "{{ s3_prefix }}{{ username }}-kubeconfig.yaml"
    src: "/tmp/{{ username }}-kubeconfig.yaml"
    mode: put
  register: s3_upload


- name: "Generate presigned URL for kubeconfig"
  command: >
    aws s3 presign s3://{{ s3_bucket }}/{{ s3_prefix }}{{ username }}-kubeconfig.yaml --expires-in 43200
  register: presigned_url_cmd

- set_fact:
    kubeconfig_url: "{{ presigned_url_cmd.stdout }}"

